# Vale configuration root
StylesPath = .styles/
MinAlertLevel = suggestion

Packages = write-good, proselint

[formats]
mdx = md

[*]
BasedOnStyles = VijilStyle, Vale, write-good, proselint

Markdown.IgnoreFrontMatter = YES
Markdown.IgnoreCodeBlocks = YES

write-good.E-Prime = NO
write-good.So = suggestion
write-good.ThereIs = suggestion